Rails.application.routes.draw do

# we only want 2 routes so we added the restriction only
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]

  # root path will only be active if nothing above it matches the route
  root to: 'visitors#new'

end

# new route has these properties
# new_visitor_path - route helper
# visitors - name of controller
# new - controller action
# localhost:3000/visitors/new - url generated by the route helper
# get - http method to display a page
